#!/usr/bin/env python3
"""Deterministic data extraction script generated by DataAgent.

Run ID: phase2-d7293030c6dd
Source: fedstat / 40566
Generated: 2026-05-12T09:56:35Z

Usage:
    python script-c9913ae9.py

This script reproduces the extraction without LLM involvement.
All numeric values come exclusively from deterministic source adapters.
"""
from __future__ import annotations

import json
from pathlib import Path

from app.data.fedstat_adapter import extract_fedstat_dataset


def main() -> None:
    output_dir = Path("./extracted_data")
    output_dir.mkdir(parents=True, exist_ok=True)

    source_card = {
        "source_family": "fedstat",
        "dataset_id": "40566",
        "resource_id": "40566",
    }
    filters = {'geography': 'Российская Федерация', 'countries': ['Russia'], 'indicator': 'ВВП по ППС', 'period': ['1995', '1996', '1997', '1998', '1999']}

    # Operations from extraction plan: ['filter_rows', 'export_dataset']
    print(f"Extracting {source_card['dataset_id']} with filters: {filters}")

    # NOTE: Replace the call below with the adapter matching your source family.
    # For FedStat: extract_fedstat_dataset(source_card, filters=filters, ...)
    # For World Bank: extract_world_bank_dataset(source_card, filters=filters, ...)
    # For CKAN: promoted = promote_ckan_package(source_id); extract_ckan_dataset(promoted, ...)
    print("Extraction script ready. Configure source-specific parameters above.")
    print(f"Output directory: {output_dir}")


if __name__ == "__main__":
    main()
