#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.catalog.source_catalog import SourceCatalog


DEFAULT_CATALOG = Path(".local/dataagent/phase1/source-catalog.sqlite")
DEFAULT_MANIFEST = Path(
    ".planning/phases/01-data-architecture-research/source-catalog-manifest.json"
)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Build the local SQLite/DuckDB catalog interface for source_cards and embedding_chunks."
    )
    parser.add_argument(
        "--source-cards-manifest",
        type=Path,
        required=True,
        help="Manifest generated by scripts/build_source_cards.py.",
    )
    parser.add_argument("--catalog", type=Path, default=DEFAULT_CATALOG)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    args = parser.parse_args()

    cards = load_cards_from_manifest(args.source_cards_manifest)
    manifest = build_source_catalog(
        cards,
        catalog_path=args.catalog,
        manifest_path=args.manifest,
        source_cards_manifest=args.source_cards_manifest,
    )
    print(f"Wrote SourceCatalog SQLite database to {args.catalog}")
    print(f"Wrote source catalog manifest to {args.manifest}")
    print(json.dumps({"source_cards_count": manifest["source_cards_count"]}, sort_keys=True))


def load_cards_from_manifest(manifest_path: Path) -> list[dict[str, Any]]:
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    artifact_path = Path(manifest["artifact_path"])
    payload = json.loads(artifact_path.read_text(encoding="utf-8"))
    cards = payload.get("cards", [])
    if not isinstance(cards, list) or not cards:
        raise RuntimeError(f"No source cards found in {artifact_path}")
    return cards


def build_source_catalog(
    cards: list[dict[str, Any]],
    *,
    catalog_path: Path,
    manifest_path: Path,
    source_cards_manifest: Path,
) -> dict[str, Any]:
    catalog = SourceCatalog(catalog_path)
    catalog.rebuild(cards)
    queryability = catalog.queryable()
    table_counts = catalog.table_counts()
    manifest = {
        "catalog_type": "SQLite",
        "duckdb_compatible": True,
        "catalog_path": str(catalog_path),
        "manifest_path": str(manifest_path),
        "source_cards_manifest": str(source_cards_manifest),
        "tables": ["source_cards", "coverage_hints", "embedding_chunks", "rejection_metadata"],
        "table_counts": table_counts,
        "source_cards_count": table_counts["source_cards"],
        "embedding_chunks_count": table_counts["embedding_chunks"],
        "source_families": catalog.source_families(),
        "queryability_check": "passed" if queryability else "failed",
        "content_hash": hashlib.sha256(catalog_path.read_bytes()).hexdigest(),
        "local_artifacts": [str(catalog_path)],
        "rejection_metadata": "available",
    }
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return manifest


if __name__ == "__main__":
    main()
