#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.artifacts.source_cards import EmbeddingCorpusManifest, SourceCandidateCard


DEFAULT_ARTIFACT = Path(".local/dataagent/phase1/embedding-corpus.jsonl")
DEFAULT_MANIFEST = Path(
    ".planning/phases/01-data-architecture-research/embedding-corpus-manifest.json"
)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Build deterministic EmbeddingDocument source-card chunks without calling embeddings."
    )
    parser.add_argument(
        "--source-cards-manifest",
        type=Path,
        required=True,
        help="Manifest generated by scripts/build_source_cards.py.",
    )
    parser.add_argument("--output", type=Path, default=DEFAULT_ARTIFACT)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    args = parser.parse_args()

    cards = load_cards_from_manifest(args.source_cards_manifest)
    manifest = build_embedding_corpus(cards, artifact_path=args.output, manifest_path=args.manifest)
    print(f"Wrote {manifest['chunk_count']} embedding chunks to {args.output}")
    print(f"Wrote embedding corpus manifest to {args.manifest}")


def load_cards_from_manifest(manifest_path: Path) -> list[dict[str, Any]]:
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    artifact_path = Path(manifest["artifact_path"])
    payload = json.loads(artifact_path.read_text(encoding="utf-8"))
    cards = payload.get("cards", [])
    if not isinstance(cards, list) or not cards:
        raise RuntimeError(f"No source cards found in {artifact_path}")
    return cards


def build_embedding_corpus(
    cards: list[dict[str, Any]],
    *,
    artifact_path: Path,
    manifest_path: Path,
) -> dict[str, Any]:
    parsed_cards = [SourceCandidateCard.model_validate(card) for card in cards]
    documents = [card.to_embedding_chunk().model_dump(mode="json") for card in parsed_cards]
    documents.sort(key=lambda item: item["chunk_id"])
    artifact_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [json.dumps(document, ensure_ascii=False, sort_keys=True) for document in documents]
    artifact_path.write_text("\n".join(lines) + ("\n" if lines else ""), encoding="utf-8")

    corpus_bytes = artifact_path.read_bytes()
    chunk_hashes = {
        str(document["chunk_id"]): hashlib.sha256(
            json.dumps(document, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode("utf-8")
        ).hexdigest()
        for document in documents
    }
    manifest_model = EmbeddingCorpusManifest(
        artifact_path=str(artifact_path),
        manifest_path=str(manifest_path),
        chunk_count=len(documents),
        source_families=sorted({str(document["source_family"]) for document in documents}),
        content_hash=hashlib.sha256(corpus_bytes).hexdigest(),
        chunk_hashes=chunk_hashes,
        local_artifacts=[str(artifact_path)],
    )
    manifest = manifest_model.model_dump(mode="json")
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return manifest


if __name__ == "__main__":
    main()
