#!/usr/bin/env python3
"""Deterministic data extraction script generated by DataAgent.

Run ID: phase2-4ed7b5414f52
Source: world_bank / NE.CON.PRVT.PP.CD
Generated: 2026-05-11T23:20:43Z

Usage:
    python script-4bf45b70.py

This script reproduces the extraction without LLM involvement.
All numeric values come exclusively from deterministic source adapters.
"""
from __future__ import annotations

import json
from pathlib import Path

from app.data.world_bank_adapter import extract_world_bank_dataset


def main() -> None:
    output_dir = Path("./extracted_data")
    output_dir.mkdir(parents=True, exist_ok=True)

    source_card = {
        "source_family": "world_bank",
        "dataset_id": "NE.CON.PRVT.PP.CD",
        "resource_id": "NE.CON.PRVT.PP.CD",
    }
    filters = {'geography': 'China', 'countries': ['China'], 'indicator': 'GDP per capita', 'period': '1990-2022'}

    # Operations from extraction plan: ['filter_rows', 'export_dataset']
    print(f"Extracting {source_card['dataset_id']} with filters: {filters}")

    # NOTE: Replace the call below with the adapter matching your source family.
    # For FedStat: extract_fedstat_dataset(source_card, filters=filters, ...)
    # For World Bank: extract_world_bank_dataset(source_card, filters=filters, ...)
    # For CKAN: promoted = promote_ckan_package(source_id); extract_ckan_dataset(promoted, ...)
    print("Extraction script ready. Configure source-specific parameters above.")
    print(f"Output directory: {output_dir}")


if __name__ == "__main__":
    main()
